# Generated by Django 5.0.4 on 2024-06-06 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_client_phone'),
        ('app', '0012_remove_client_address_client_city'),
    ]

    operations = [
    ]
